from __future__ import annotations

from typing import Any


class FundCollaborativeSignalService:
    """
    Calculates a collaborative recommendation signal.

    The service does not invent collaborative behavior. A signal is
    produced only when genuine peer-interaction evidence is supplied.

    Expected peer evidence for each fund:
        {
            "scheme_code": "...",
            "similar_user_count": 10,
            "interaction_count": 25,
        }

    When no evidence is available, the signal is zero and
    `available` is False.
    """

    def calculate_signal(
        self,
        scheme_code: str,
        peer_fund_activity: list[dict[str, Any]],
    ) -> dict[str, Any]:
        """
        Calculate the collaborative signal for one fund.

        Parameters
        ----------
        scheme_code:
            Official mutual-fund scheme code.

        peer_fund_activity:
            Genuine activity generated by similar users.

        Returns
        -------
        dict[str, Any]
            Collaborative signal and availability metadata.
        """

        if not scheme_code or not scheme_code.strip():
            raise ValueError("scheme_code cannot be empty")

        if not peer_fund_activity:
            return {
                "scheme_code": scheme_code.strip(),
                "signal": 0.0,
                "available": False,
                "similar_user_count": 0,
                "interaction_count": 0,
            }

        matching_records = [
            record
            for record in peer_fund_activity
            if record.get("scheme_code") == scheme_code.strip()
        ]

        if not matching_records:
            return {
                "scheme_code": scheme_code.strip(),
                "signal": 0.0,
                "available": False,
                "similar_user_count": 0,
                "interaction_count": 0,
            }

        similar_user_count = sum(
            self._non_negative_int(
                record.get("similar_user_count")
            )
            for record in matching_records
        )

        interaction_count = sum(
            self._non_negative_int(
                record.get("interaction_count")
            )
            for record in matching_records
        )

        if (
            similar_user_count <= 0
            and interaction_count <= 0
        ):
            return {
                "scheme_code": scheme_code.strip(),
                "signal": 0.0,
                "available": False,
                "similar_user_count": 0,
                "interaction_count": 0,
            }

        signal = self._normalize_activity(
            similar_user_count=similar_user_count,
            interaction_count=interaction_count,
        )

        return {
            "scheme_code": scheme_code.strip(),
            "signal": signal,
            "available": True,
            "similar_user_count": similar_user_count,
            "interaction_count": interaction_count,
        }

    @staticmethod
    def _non_negative_int(value: Any) -> int:
        if value is None:
            return 0

        try:
            number = int(value)
        except (TypeError, ValueError):
            return 0

        return max(0, number)

    @staticmethod
    def _normalize_activity(
        *,
        similar_user_count: int,
        interaction_count: int,
    ) -> float:
        """
        Convert peer activity into a bounded 0-1 signal.

        Similar-user breadth receives more importance than raw interaction
        volume so that repeated activity from a very small peer group does
        not dominate the signal.
        """

        user_signal = min(
            1.0,
            similar_user_count / 20.0,
        )

        interaction_signal = min(
            1.0,
            interaction_count / 50.0,
        )

        signal = (
            user_signal * 0.70
            + interaction_signal * 0.30
        )

        return round(
            signal,
            6,
        )