class DemoLLMService:

    def generate_response(self, prompt, model):

        # Simulated LLM response
        response = (
            f"Demo response generated by {model} "
            f"for the prompt: {prompt}"
        )

        # Simulated token usage
        input_tokens = max(1, len(prompt.split()) * 2)
        output_tokens = max(1, len(response.split()))

        total_tokens = (
            input_tokens + output_tokens
        )

        return {
            "response": response,
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "total_tokens": total_tokens
        }